import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Card from "../components/card";
import path from "path";
import { promises as fs } from "fs";

export default function Home(props) {
  const { data } = props;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.wrapper}>
         {data.map((item,index) => {return(
           <Card
           key={index}
           name={item.name}
           username={item.username}
           background_image={item.background_image}
           profile_image={item.profile_image}
           caption={item.caption}
           follower={item.follower}
           profession={item.profession}
         />
         )
          ;
        })}
      
      </main>
    </div>
  );
}

export async function getStaticProps(context) {
  const filepath = path.join(process.cwd(), "database", "user.json");
  const jsonData = await fs.readFile(filepath);
  const data = JSON.parse(jsonData);
  return {
    props: {
      data,
    },
  };
}
